name: SanicDNS Scan

on:
  push:
    paths:
      - 'subdomains.txt'
      - 'resolvers.txt'
  workflow_dispatch:

jobs:
  build-and-resolve:
    runs-on: ubuntu-latest

    steps:
      # 1. Grab your code (including subdomains.txt & resolvers.txt)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install all prerequisites in one go
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          python3 \
          libelf-dev \
          dpdk \
          dpdk-dev \
          libncurses5-dev \
          liburing-dev \
          software-properties-common \
          linux-headers-generic \
          libbpf-dev \
          libc6-dev \
          libc6-dev-i386 \
          libxdp-dev \
          clang-17

      # 3. Clone & compile SanicDNS
      - name: Clone sanicdns & build
        run: |
          git clone --recursive https://github.com/hadriansecurity/sanicdns.git
          cd sanicdns
          mkdir -p build
          cmake -B build \
            -DCMAKE_GENERATOR=Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=ci/clang-toolchain.cmake \
            -DNIC_TYPE=AF_XDP
          ninja -C build

      # 4. Run the scanner against your input lists
      - name: Run SanicDNS
        run: |
          # assumes subdomains.txt & resolvers.txt are in the repo root
          ./sanicdns/build/sanicdns \
            -d subdomains.txt \
            -r resolvers.txt \
            -o sanicdns-results.txt

      # 5. Upload the scan output for later inspection
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: sanicdns-results
          path: sanicdns-results.txt
