name: SanicDNS CI

on:
  push:
    paths:
      - 'subdomains.txt'
      - 'resolvers.txt'
      - '.github/workflows/sanicdns.yml'
  workflow_dispatch:

jobs:
  build-and-run:
    name: Build & Run SanicDNS
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        shell: bash
        run: |
          curl -sSL https://raw.githubusercontent.com/hadriansecurity/sanicdns/main/install.sh | sudo bash

      - name: Allocate hugepages (1 GB)
        run: |
          # best-effort; if dpdk-hugepages.py isn't on PATH this will fail harmlessly
          sudo dpdk-hugepages.py --setup 1G || true

      - name: Verify installation
        run: |
          which sanicdns
          sanicdns --help

      - name: Run SanicDNS against your lists
        run: |
          sudo sanicdns \
            -i subdomains.txt \
            --postfix .navy.mil \
            -r 2000 \
            -c 10000 \
            --resolvers resolvers.txt \
            -o out.txt \ 
            --num-retries 15   

      - name: Upload logs and output
        uses: actions/upload-artifact@v4
        with:
          name: sanicdns-results
          path: |
            out.txt
            
