

on:
  push:
    paths:
      - 'subdomains.txt'
      - 'resolvers.txt'
      - '.github/workflows/sanicdns.yml'
  workflow_dispatch:

jobs:
  build-and-run:
    name: Build & Run SanicDNS
    runs-on: ubuntu-latest
    env:
      TERM: xterm    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        shell: bash
        run: |
          curl -sSL https://raw.githubusercontent.com/hadriansecurity/sanicdns/main/install.sh | sudo bash
     
      - name: Install ethtool & shrink NIC queues
        run: |
          sudo apt-get update
          sudo apt-get install -y ethtool
          # If eth0 doesn’t exist, adjust the interface name accordingly
          sudo ethtool -L eth0 combined 3 || true          
      - name: Allocate hugepages (1 GB)
        run: |
          # best-effort; if dpdk-hugepages.py isn't on PATH this will fail harmlessly
          sudo dpdk-hugepages.py --setup 2G || true
      - name: Verify installation
        run: |
          which sanicdns
          
          
      - name: Run SanicDNS against your lists
        run: |
          export TERM=xterm         
          wget https://raw.githubusercontent.com/hadriansecurity/sanicdns/main/majestic_million.txt
          sudo sanicdns \
            -i majestic_million.txt \
            -r 5000 \
            -c 20000 \
            -l log.txt \
            --resolvers resolvers.txt \
            -o out.txt \
            -w 4 \
            --num-retries 10 \
            --timeout 15000
 

      - name: Upload logs and output
        uses: actions/upload-artifact@v4
        with:
          name: sanicdns-results
          path: |
            out.txt
            log.txt
